services:
  openbao:
    image: openbao/openbao:latest
    container_name: ngelmak-openbao
    ports:
      - "8200:8200"
    environment:
      # OpenBao needs to know where to store data
      OPENBAO_DEV_ROOT_TOKEN_ID: root
      OPENBAO_DEV_LISTEN_ADDRESS: "0.0.0.0:8200"
    volumes:
      - ./data:/data
      - ./config:/etc/openbao
    command: server -config=/etc/openbao/config.hcl
    networks:
      - ngelmak-net

networks:
  ngelmak-net:
    external: true