services:
  # ---  Ngelmak Vault ---
  vault:
    image: openbao/openbao:latest
    container_name: vault
    user: "1000:1000" # Run the container as the vault user (UID 1000) and group (GID 1000)
    ports:
      - "8200:8200"
    volumes:
    - /var/lib/containers-data/vault/data:/data # Mount the data directory for Vault to persist its data
    - /var/lib/containers-data/vault/config:/etc/openbao # Mount the configuration directory for Vault to read its configuration
    - /var/lib/containers-data/vault/home:/home/vault # Mount the home directory for the vault user to store any necessary files
    environment:
      HOME: /home/vault # Set the HOME environment variable for the vault user
      VAULT_ADDR: "http://127.0.0.1:8200" # Vault server address for clients to connect to
    command: server -config=/etc/openbao/config.hcl
    networks:
      - ngelmak-net

networks:
  ngelmak-net:
    external: true